<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '1',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '5999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '1',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '6099',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '1',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '7799',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '1',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '7999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '1',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '5950',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '6599',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4325',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '8000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '1299',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '13200',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '15000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '7999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '3',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '1299',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            
            
            
            
            
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '34999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '9999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '5499',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4599',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '5999',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '4',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4799',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '5',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '6',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '6',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '6',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '6',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '6',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '8',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '9',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '10',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            
            
            
            
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
            [
                'title' => 'product Brand Model 4586 K72J',
                'category_id' => '11',
                'manufacturer_id' => random_int(1, 10),
                'image' => '1-0.jpg',
                'code' => random_int(100000, 999999),
                'price' => '4699',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
            ],
        ]);
    }
}
